/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JS 側 DeviceInfo。`sourceKind` は文字列（"mic"|"system"|"process"）。 */
export interface JsDeviceInfo {
  id: string
  name: string
  sourceKind: string
  sampleRate: number
  channels: number
  isLoopback: boolean
  isDefault: boolean
}
/**
 * JS 側 AudioChunk。`data` は interleaved f32（len = frames * channels）。
 * `seq`(u64) は精度欠落を避けて BigInt。`flags` は ChunkFlags のビット(u32)。
 *
 * `vadEvents` は `openStream` に `vad` を指定したときだけ埋まる。VAD 無効時は未設定
 * （`undefined`）。有効でもそのチャンクで確定イベントが無ければ空配列になる。
 */
export interface JsAudioChunk {
  data: Float32Array
  frames: number
  ptsNs: number
  seq: bigint
  flags: number
  droppedBefore: number
  peak: number
  rms: number
  /** このチャンクで確定した VAD イベント（`vadTap` が 'primary' のときのみ）。 */
  vadEvents?: Array<JsVadEvent>
  /**
   * 時刻対応する副タップチャンク（`secondaryOutput` 設定時のみ）。同一コールバックで
   * ペア配送する（`onChunk(primary)` の `primary.secondary`）。副が未達の周回は
   * `undefined`。主↔副の対応は `ptsNs`（時刻）で取ること（`seq` は各タップ独立）。
   */
  secondary?: JsSecondaryChunk
}
/**
 * JS 側の副タップチャンク（`secondaryOutput` 設定時のみ）。
 *
 * `data` は `encoding` に一致する typed array（`'s16'` なら `Int16Array`、`'f32'` なら
 * `Float32Array`）。サンプル値はホストのネイティブエンディアン。s16le の wire 形式へ
 * 直列化するのは受け手（消費側）の責務。`ptsNs` は主と同じ録音 0 起点時計に乗るが、値は
 * 主とは独立で、副 Stage2 のリサンプラ群遅延ぶん主より 20〜60ms 遅れる。
 */
export interface JsSecondaryChunk {
  data: Int16Array | Float32Array
  /** 'f32' | 's16'（`data` の型を絞り込むための判別子）。 */
  encoding: string
  frames: number
  ptsNs: number
  seq: bigint
  flags: number
  droppedBefore: number
  /** 量子化前 f32 で算出（s16 でもメーター精度を落とさない）。 */
  peak: number
  rms: number
  /** このチャンクで確定した VAD イベント（`vadTap` が 'secondary' のときのみ）。 */
  vadEvents?: Array<JsVadEvent>
}
/**
 * JS 側 VAD イベント（発話区間の開始/終了）。
 *
 * `type` は `'speechStart' | 'speechEnd'` の 2 値のみ（他イベントの `type` と統一）。
 *
 * `atSample` は **VAD の内部レート（`sampleRate`＝8000 か 16000、既定 16000）基準**の
 * 絶対サンプル位置で、入力チャンクのサンプル基準ではない（silero 生値・単体/デバッグ用）。
 * 秒に直すなら `atSample / sampleRate`、入力サンプル位置の目安は
 * `atSample * inputSampleRate / sampleRate` で近似できる。
 */
export interface JsVadEvent {
  /** 'speechStart' | 'speechEnd'（発話区間の開始/終了）。 */
  type: 'speechStart' | 'speechEnd'
  atSample: number
  /**
   * 録音 0 起点の絶対ナノ秒（`number`＝f64）。統合 VAD（`openStream` の `vad`）経由でのみ
   * 埋まる（チャンクの `ptsNs` とチャンク内オフセットから F4 再基準化式で算出）。同一
   * チャンクで配送され、チャンクをまたいで単調非減少。`flushVad` の最終イベントも同じ
   * `vadEvents` 配列に載る。単体 `Vad` クラス（`process`/`flush`）は pts 文脈が無いため
   * `undefined`。（時刻は録音長で有界なので `number`。生 u64 カウンタの `seq` のみ `bigint`。）
   */
  atNs?: number
}
/** JS 側ネイティブフォーマット（`FlexStream.nativeFormat` の戻り）。 */
export interface JsNativeFormat {
  sampleRate: number
  channels: number
}
/**
 * 統合 VAD の設定（`OpenOptions.vad` と `Vad` コンストラクタが共有）。
 *
 * 各フィールドは省略可で、省略時は silero 準拠の既定値（`VadConfig::default`）。
 */
export interface VadOptions {
  /** 発話開始とみなす確率しきい値 (>=)。既定 0.5。 */
  threshold?: number
  /** 無音開始とみなす負側しきい値 (<)。省略時は `max(threshold - 0.15, 0.01)`。 */
  negThreshold?: number
  /** 採用する発話の最小長 (ms)。既定 250。 */
  minSpeechMs?: number
  /** 発話終了の確定に必要な無音長 (ms)。既定 100。 */
  minSilenceMs?: number
  /** セグメント境界を前後に広げるパディング (ms)。既定 30。 */
  speechPadMs?: number
  /**
   * 1 セグメントの最大長 (ms)。0 = 無制限。超過時は強制分割。
   *
   * 単体 `Vad` クラスは silero 忠実で既定 0（無制限）。**統合 VAD（`openStream` の `vad`）は
   * 省略時 30000ms（長広舌を有界化して RT 遅延を抑える）**。明示指定（`0` を含む）があれば
   * それが勝つ。
   */
  maxSpeechMs?: number
  /** VAD の内部サンプルレート。8000 または 16000 のみ。既定 16000。 */
  sampleRate?: number
}
/** JS 側ストリームイベント。`type` で種別、`count`/`message` は任意。 */
export interface JsStreamEvent {
  type: string
  count?: number
  message?: string
}
/** JS 側デバイスイベント。`type` で種別、device/id/sourceKind は任意。 */
export interface JsDeviceEvent {
  type: string
  device?: JsDeviceInfo
  id?: string
  sourceKind?: string
}
/**
 * 副出力タップの指定（`OpenOptions.secondaryOutput`）。
 *
 * 主出力（`outputRate`/`outputChannels`）と同じキャプチャを別フォーマットで同時に返す。
 * 保存 48k/stereo + 認識 16k/mono/s16 のようなペア取得に使う。
 */
export interface SecondaryOutputOptions {
  /** 副出力サンプルレート（Hz）。例 16000。 */
  rate: number
  /** 副出力チャンネル数（1=mono / 2=stereo）。例 1。 */
  channels: number
  /**
   * 副チャンクのサンプルエンコーディング。'f32'（既定）| 's16'。s16 は VAD の後に
   * 量子化して `Int16Array` で返す（値はネイティブエンディアン）。
   */
  encoding?: string
}
/** openStream / __openMockStream のオプション。 */
export interface OpenOptions {
  /** "mic" | "system" | "process" | "mix" */
  kind: string
  deviceId?: string
  processId?: number
  /**
   * process の対象 PID の扱い（process 専用）。"include"（既定）| "exclude"。
   * include=対象 PID だけ録る / exclude=対象 PID 以外の全システム音（process_id 必須）。
   * mic / system では無視。Linux / Windows / macOS の 3 OS とも対応。
   */
  mode?: string
  /**
   * システム音から自ホスト（自プロセス）の音を除くか（system 専用。mix では
   * system 側に適用）。既定 false。mic / process では無視。
   * Linux / Windows / macOS の 3 OS とも対応。
   */
  excludeSelf?: boolean
  /** 既定 48000 */
  outputRate?: number
  /** 既定 2 */
  outputChannels?: number
  /** 既定 20 */
  chunkMs?: number
  /**
   * 開始時の入力ゲイン（線形倍率）。既定 1.0。1.0=そのまま、2.0=約+6dB、0.0=無音。
   * 実行時変更は `setGain`。
   */
  gain?: number
  /** mix の mic 側で選ぶ入力デバイス ID（mix 専用）。未指定なら既定入力。 */
  micDeviceId?: string
  /** mix の system 側で選ぶ出力エンドポイント ID（mix 専用）。未指定なら既定出力。 */
  systemDeviceId?: string
  /** mix の mic 側の合成前倍率（線形・mix 専用）。既定 1.0。合成後に `gain` が掛かる。 */
  micGain?: number
  /** mix の system 側の合成前倍率（線形・mix 専用）。既定 1.0。 */
  systemGain?: number
  /**
   * 統合 VAD の設定。指定すると `vadTap` で選んだタップを VAD に通し、確定イベントを
   * そのタップのチャンクの `vadEvents` に添える（音声自体は加工しない）。省略時は VAD 無効。
   */
  vad?: VadOptions
  /**
   * VAD を走らせるタップ。'primary'（既定）| 'secondary'。'secondary' は
   * `secondaryOutput` 設定時のみ有効で、副が 16k/mono ならリサンプル省略で効率的。
   */
  vadTap?: string
  /**
   * true で録音時ノイズ抑制を有効化。**出力が 48000 Hz のときだけ使える**
   * （RNNoise は 48kHz 固定）。有効時は 48kHz/stereo の内部正規形へ 1 度だけ適用され、
   * 主・副の両タップが除去済み音声を受ける（+10ms の固定遅延）。48kHz 以外で true に
   * すると `openStream` が InvalidArg を投げる。省略/false でノイズ抑制なし。
   */
  denoise?: boolean
  /**
   * 副出力タップ。指定すると主とペアで別フォーマットのチャンクを同時に返す
   * （`onChunk` の `primary.secondary`）。省略時は副タップなし＝従来どおり。
   */
  secondaryOutput?: SecondaryOutputOptions
}
/** 利用可能なデバイスを列挙する。ヘッドレス環境では空配列でも throw しない。 */
export declare function devices(): Array<JsDeviceInfo>
/**
 * ストリームを開いて開始し、チャンク/イベントをコールバックへ送る `FlexStream` を返す。
 *
 * `options.denoise` を指定すると core（内部正規形）でノイズ抑制が有効になり、主・副の両
 * タップが除去済み音声を受ける。`options.vad` を指定すると `vadTap` で選んだタップを VAD に
 * 通し、確定イベントをそのタップのチャンクの `vadEvents`（録音 0 起点の絶対時刻 `atNs` 付き）
 * に添える。`options.secondaryOutput` を指定すると副タップが有効になり、主とペアで別
 * フォーマットのチャンクを返す（`onChunk` の `primary.secondary`）。denoise の 48kHz 前提や
 * VAD 設定の不正は、ここでストリームを開く前に検証して弾く。
 *
 * Standard operation enables the secondary tap and VAD for the entire recording.
 * Toggle transcription by keeping or discarding the delivered results, not by
 * re-opening the stream; the secondary format is fixed at open (see
 * `switchSource`), so the recognition resample + VAD run on every recording —
 * budget for them as a constant cost, not an opt-in. The integrated VAD defaults
 * `maxSpeechMs` to 30 s so a monologue with no silence stays bounded; call
 * `flushVad` to force-close the open utterance (e.g. when pausing recognition).
 * Per-chunk `vadEvents[].atNs` is a recording zero-based absolute time that is
 * monotonic non-decreasing across chunks.
 */
export declare function openStream(options: OpenOptions, onChunk: ChunkTsfn, onEvent?: EventTsfn | undefined | null): FlexStream
/** デバイス着脱を監視し、イベントをコールバックへ送る `DeviceWatcherHandle` を返す。 */
export declare function watchDevices(onEvent: DeviceTsfn): DeviceWatcherHandle
/**
 * テスト専用・公開 API 外。
 *
 * 低レベル `Stream::open` に `MockBackend` を渡してストリームを作り、`open_stream` と
 * 同じ bridge / TSFN 経路で回す。実音なしで marshaling 全経路（Float32Array・BigInt・
 * peak/rms・frames）を end-to-end 検証する。本番コードからは使わないこと。
 *
 * `secondaryRate` を渡すと副タップ（`secondaryChannels`＝既定 1・`secondaryEncoding`＝
 * 'f32'|'s16'、既定 'f32'）を有効化し、ペア合成・s16 量子化・`Int16Array` を検証できる。
 * `vadThreshold` を渡すと統合 VAD（`vadTap`＝'primary'|'secondary'、既定 'primary'）を
 * 有効化し、`flushVad`・`vadEvents` の `atNs`・`stop()` 自動 flush を検証できる。
 *
 * JS 名は `__openMockStream`。先頭 `__` で公開 API 外を示す。napi の既定変換は先頭
 * アンダースコアを落として `openMockStream` にしてしまうので `js_name` で固定する。
 */
export declare function __openMockStream(sampleRate: number, channels: number, freqHz: number, onChunk: ChunkTsfn, secondaryRate?: number | undefined | null, secondaryChannels?: number | undefined | null, secondaryEncoding?: string | undefined | null, vadThreshold?: number | undefined | null, vadTap?: string | undefined | null): FlexStream
/**
 * 録音ストリームのハンドル。内部で bridge スレッドが `flexaudio::Stream` を
 * 所有・ポーリングし、チャンク/イベントを TSFN 経由で JS へ送る。
 */
export class FlexStream {
  /** 録音を停止し bridge スレッドを join する。二重呼び出し安全。 */
  stop(): void
  /**
   * 録音を止めずに入力ソース（mic/system/process）をホットスワップする。
   *
   * `options` から構築した `StreamConfig` への切替を bridge スレッドへ依頼し、結果を
   * 同期的に返す（成功で `Ok`、失敗で例外）。出力フォーマット（`outputRate`/
   * `outputChannels`）は切替では変えられない（連続ストリームの frames が変わるため）。
   * 変更を要求すると `switch_source` が InvalidArg を返し、ここで例外になる。切替前後で
   * チャンクの `seq` は連続し、切替後最初のチャンクには DISCONTINUITY フラグが立つ。
   * `options.gain` は無視される（ゲインはストリームの状態。変更は `setGain`）。
   *
   * 既に `stop()` 済み（bridge スレッド停止後）なら例外を返す。
   */
  switchSource(options: OpenOptions): void
  /**
   * 録音を一時停止する。デバイスは動かしたまま配信だけ止める。`resume` で再開し、
   * 再開後の最初のチャンクに DISCONTINUITY が立つ。既に `stop()` 済みなら例外。
   */
  pause(): void
  /** 一時停止を解除して配信を再開する。既に `stop()` 済みなら例外。 */
  resume(): void
  /**
   * 統合 VAD の「今開いている発話」を強制的に確定する（runtime 操作）。
   *
   * silero は無音が来ない限り `speechEnd` を出さないので、認識を一時停止する・録音末尾で
   * 最後の発話を確定したいときにこれを呼ぶ。開いている発話があれば最終 `speechEnd`（と対の
   * `speechStart`）が、次に届くタップのチャンクの `vadEvents`（録音 0 起点 `atNs` 付き）
   * 先頭に載る（20ms 毎にチャンクが流れるので遅延 ≤ 1 チャンク）。呼び出し後 VAD は
   * リセットされ、次の発話は新しい文脈で拾う。
   *
   * これは config を変えない（`secondaryOutput`/encoding の open 時固定＝`switchSource` で
   * 変更不可、とは無関係）。また音の stop-flush とは別物で、音サンプルは加工しない。VAD
   * 未設定なら何もしない。`stop()` は音の stop-flush の後にこれを自動実行する。既に `stop()`
   * 済みなら例外。
   */
  flushVad(): void
  /**
   * 入力ゲイン（線形倍率）を変更する。1.0=そのまま、2.0=約+6dB、0.0=無音。録音中
   * いつでも呼べて、次のチャンクから効く（設定されたチャンク粒度）。乗算後のサンプルは ±1.0 に
   * クランプされる。有限かつ 0 以上でなければ例外。既に `stop()` 済みなら例外。
   */
  setGain(gain: number): void
  /** 現在ポーズ中かどうか。既に `stop()` 済みなら例外。 */
  isPaused(): boolean
  /** 現在の入力ゲイン（線形倍率）。既に `stop()` 済みなら例外。 */
  gain(): number
  /**
   * 現在の backend のネイティブフォーマット `{ sampleRate, channels }`。表示・診断用
   * （実際に配信されるチャンクは出力フォーマット `outputRate`/`outputChannels`）。
   * `switchSource` でソースを変えると新 backend の値に更新される。既に `stop()` 済み
   * なら例外。
   */
  nativeFormat(): JsNativeFormat
  /**
   * チャンクリングが DROP_OLDEST で捨てた累計チャンク数（BigInt）。既に `stop()` 済み
   * なら例外。
   */
  droppedChunks(): bigint
}
/** デバイス着脱監視のハンドル。bridge スレッドが `DeviceWatcher` を poll する。 */
export class DeviceWatcherHandle {
  /** 監視を停止し bridge スレッドを join する。二重呼び出し安全。 */
  stop(): void
}
/**
 * オフライン VAD（silero-VAD on ONNX、モデル埋め込み）のハンドル。
 *
 * 1 インスタンスが ONNX セッションを 1 つ持つ。任意フォーマット（`inputSampleRate` /
 * `inputChannels` の interleaved f32）を [`Vad::process`] に流すと、内部で VAD レートの
 * mono に変換してから発話区間を検出し、確定した [`JsVadEvent`] を返す。`openStream` の
 * 統合 VAD を使わず、任意のサンプル列を自前で判定したいときに使う。
 */
export class Vad {
  /**
   * 設定オブジェクトから VAD を構築する（埋め込みモデルをロードする）。設定が不正
   * （sampleRate が 8000/16000 以外、threshold が `[0,1]` 外など）なら InvalidArg、
   * モデルロード失敗なら GenericFailure。
   */
  constructor(options: VadOptions)
  /**
   * 任意フォーマットの interleaved f32 を処理し、確定した [`JsVadEvent`] を返す。
   *
   * 端数フレームは内部に持ち越すので任意の位置で分割して渡してよい。`atSample` は
   * VAD 内部レート基準（[`JsVadEvent`] を参照）。
   */
  process(samples: Float32Array, inputSampleRate: number, inputChannels: number): Array<JsVadEvent>
  /**
   * 今開いている発話を強制的に確定し、確定した [`JsVadEvent`] を返す（入力終端に達したのと
   * 同じ挙動）。呼び出し後は内部状態がリセットされ、次の `process` は新しい文脈から始まる。
   * モデル推論は走らないので軽量・決定的。
   *
   * 単体 `Vad` は pts 文脈を持たないので `atNs` は `undefined`（`atSample` は VAD 内部レート
   * 基準の生の累積位置）。無発話中は空配列を返す。
   */
  flush(): Array<JsVadEvent>
  /** 内部状態（state / context / 状態機械 / サンプル位置 / リサンプラ）を初期化する。 */
  reset(): void
}
/**
 * 録音チャンクを逐次 FLAC ファイルへ可逆圧縮保存するライター。
 *
 * `splitSeconds` を 1 以上にすると、書き込みフレーム数が `splitSeconds × sampleRate` に
 * 達するたびに現在のファイルを閉じ、`name-001.flac, name-002.flac, …` と 3 桁連番で
 * 次ファイルへローテーションする（CLI の WAV 分割と同じ流儀）。境界はチャンク粒度の
 * 「以上で次へ」なので、各ファイルは指定秒より最大 1 チャンク長くなりうるが、チャンクは
 * 分割されず取りこぼしも無い。`splitSeconds` 省略/0 なら単一ファイル。
 */
export class FlacEncoder {
  /**
   * FLAC ライターを作る。`splitSeconds` 省略/0 で単一ファイル、1 以上で秒数ローテ。
   *
   * `channels` は 1..=2、`sampleRate` は 1..=96000 Hz（範囲外は InvalidArg）。分割時は
   * 最初のファイル（`name-001.flac`）を即作成する。
   */
  static create(path: string, sampleRate: number, channels: number, splitSeconds?: number | undefined | null): FlacEncoder
  /**
   * interleaved f32（長さは `channels` の倍数）を追記する。倍数でなければ InvalidArg。
   *
   * 書き込み後、現在のファイルのフレーム数がしきい値以上なら即 finalize して次ファイルへ
   * ローテーションする（次の `writeChunk` が新ファイルの先頭になる）。
   */
  writeChunk(samples: Float32Array): void
  /**
   * 端数を書き切ってヘッダを確定し、開いているファイルを閉じる。二重呼び出し安全
   * （2 回目以降は no-op）。呼ばずに捨てても `FlacWriter` の Drop がベストエフォートで
   * 閉じるが、書き込みエラーを検知したいならこれを呼ぶこと。
   */
  finalize(): void
}
/**
 * オフラインのノイズ抑制器（RNNoise via nnnoiseless、重み埋め込み）。**48kHz 前提**で、
 * マイク録音の定常ノイズ（ファン・空調・打鍵など）の低減を想定する。
 *
 * [`FRAME_SIZE`](flexaudio_denoise::FRAME_SIZE)（48kHz で 10ms）固定の遅延があり、出力は
 * 入力を 1 フレーム分遅らせた列になる。ストリーム先頭の 1 フレームは無音の詰め物で、
 * 末尾に残る 1 フレーム分は [`Denoiser::flush`] で取り出す。
 */
export class Denoiser {
  /**
   * チャンネル数（1 = mono, 2 = stereo interleaved）を指定して構築する。範囲外は
   * InvalidArg。
   */
  constructor(channels: number)
  /**
   * 任意長の interleaved f32（±1.0 正規化・48kHz・長さは channels の倍数）を
   * ノイズ抑制して**新しい配列**で返す（napi ではインプレースが扱いにくいのでコピー）。
   * 長さが channels の倍数でなければ InvalidArg。
   */
  process(samples: Float32Array): Float32Array
  /**
   * 持ち越し中の端数を処理して末尾の遅延分（1 フレーム/ch）を返し、ストリームを閉じる。
   * 呼び出し後は生成直後と同じ状態に戻り、続けて別ストリームを処理できる。
   */
  flush(): Float32Array
  /** RNN 状態・持ち越し・遅延線をすべて初期化する。 */
  reset(): void
}
